# https://docs.cocogitto.io/reference/config.html
disable_bump_commit = true
disable_changelog = true
from_latest_tag = true
ignore_fixup_commits = true
ignore_merge_commits = true
# monorepo_version_separator = "/"
skip_ci = "ci:"
skip_untracked = true
tag_prefix = "v"

post_bump_hooks = [
  "git --no-pager push origin --tags",
]
